runtime: php55
api_version: 1
includes:
  - env_variables.yaml
handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /
  secure: always
  redirect_http_response_code: 301
  script: index.php
- url: /index.php
  secure: always
  redirect_http_response_code: 301
  script: index.php
- url: /calendar
  secure: always
  redirect_http_response_code: 301
  script: calendar_view.php
- url: /approval
  secure: always
  redirect_http_response_code: 301
  script: approval.php
- url: /weather
  secure: always
  redirect_http_response_code: 301
  script: destin_weather.php
- url: /videos
  secure: always
  redirect_http_response_code: 301
  script: videos.php
- url: /new-reservation
  secure: always
  redirect_http_response_code: 301
  script: make_reservation.php
- url: /oauth
  secure: always
  redirect_http_response_code: 301
  script: oauth-setup.php
- url: /privacy
  script: privacy-policy.html
